-- ----------------------------
-- View structure for adminservicesview
-- ----------------------------
CREATE VIEW `adminservicesview` AS select `ocadmin_dbo`.`adminservices`.`workid` AS `workid`,`ocadmin_dbo`.`adminservices`.`serviceid` AS `serviceid`,`ocadmin_dbo`.`adminservices`.`servicetype` AS `servicetype`,`ocadmin_dbo`.`adminservices`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`adminservices`.`updateserverid` AS `updateserverid` from `ocadmin_dbo`.`adminservices`;

-- ----------------------------
-- View structure for adminview
-- ----------------------------
CREATE VIEW `adminview` AS select `ocadmin_dbo`.`admin`.`personid` AS `personid`,`ocadmin_dbo`.`admin`.`immatold` AS `immatold`,`ocadmin_dbo`.`admin`.`immatnew` AS `immatnew`,`ocadmin_dbo`.`admin`.`candidate` AS `candidate`,`ocadmin_dbo`.`admin`.`lastname` AS `lastname`,`ocadmin_dbo`.`admin`.`firstname` AS `firstname`,`ocadmin_dbo`.`admin`.`gender` AS `gender`,`ocadmin_dbo`.`admin`.`dateofbirth` AS `dateofbirth`,`ocadmin_dbo`.`admin`.`comment` AS `comment`,`ocadmin_dbo`.`admin`.`sourceid` AS `sourceid`,`ocadmin_dbo`.`admin`.`language` AS `language`,`ocadmin_dbo`.`admin`.`engagement` AS `engagement`,`ocadmin_dbo`.`admin`.`pension` AS `pension`,`ocadmin_dbo`.`admin`.`statute` AS `statute`,`ocadmin_dbo`.`admin`.`claimant` AS `claimant`,`ocadmin_dbo`.`admin`.`searchname` AS `searchname`,`ocadmin_dbo`.`admin`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`admin`.`claimant_expiration` AS `claimant_expiration`,`ocadmin_dbo`.`admin`.`native_country` AS `native_country`,`ocadmin_dbo`.`admin`.`native_town` AS `native_town`,`ocadmin_dbo`.`admin`.`motive_end_of_service` AS `motive_end_of_service`,`ocadmin_dbo`.`admin`.`startdate_inactivity` AS `startdate_inactivity`,`ocadmin_dbo`.`admin`.`enddate_inactivity` AS `enddate_inactivity`,`ocadmin_dbo`.`admin`.`code_inactivity` AS `code_inactivity`,`ocadmin_dbo`.`admin`.`update_status` AS `update_status`,`ocadmin_dbo`.`admin`.`person_type` AS `person_type`,`ocadmin_dbo`.`admin`.`situation_end_of_service` AS `situation_end_of_service`,`ocadmin_dbo`.`admin`.`updateuserid` AS `updateuserid`,`ocadmin_dbo`.`admin`.`comment1` AS `comment1`,`ocadmin_dbo`.`admin`.`comment2` AS `comment2`,`ocadmin_dbo`.`admin`.`comment3` AS `comment3`,`ocadmin_dbo`.`admin`.`comment4` AS `comment4`,`ocadmin_dbo`.`admin`.`comment5` AS `comment5`,`ocadmin_dbo`.`admin`.`natreg` AS `natreg`,`ocadmin_dbo`.`admin`.`middlename` AS `middlename`,`ocadmin_dbo`.`admin`.`begindate` AS `begindate`,`ocadmin_dbo`.`admin`.`enddate` AS `enddate`,`ocadmin_dbo`.`admin`.`updateserverid` AS `updateserverid`,`ocadmin_dbo`.`admin`.`archiveFileCode` AS `archiveFileCode` from `ocadmin_dbo`.`admin`;

-- ----------------------------
-- View structure for frank
-- ----------------------------
CREATE VIEW `frank` AS select `ocadmin_dbo`.`admin`.`personid` AS `personid`,`ocadmin_dbo`.`admin`.`immatold` AS `immatold`,`ocadmin_dbo`.`admin`.`immatnew` AS `immatnew`,`ocadmin_dbo`.`admin`.`candidate` AS `candidate`,`ocadmin_dbo`.`admin`.`lastname` AS `lastname`,`ocadmin_dbo`.`admin`.`firstname` AS `firstname`,`ocadmin_dbo`.`admin`.`gender` AS `gender`,`ocadmin_dbo`.`admin`.`dateofbirth` AS `dateofbirth`,`ocadmin_dbo`.`admin`.`comment` AS `comment`,`ocadmin_dbo`.`admin`.`sourceid` AS `sourceid`,`ocadmin_dbo`.`admin`.`language` AS `language`,`ocadmin_dbo`.`admin`.`engagement` AS `engagement`,`ocadmin_dbo`.`admin`.`pension` AS `pension`,`ocadmin_dbo`.`admin`.`statute` AS `statute`,`ocadmin_dbo`.`admin`.`claimant` AS `claimant`,`ocadmin_dbo`.`admin`.`searchname` AS `searchname`,`ocadmin_dbo`.`admin`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`admin`.`claimant_expiration` AS `claimant_expiration`,`ocadmin_dbo`.`admin`.`native_country` AS `native_country`,`ocadmin_dbo`.`admin`.`native_town` AS `native_town`,`ocadmin_dbo`.`admin`.`motive_end_of_service` AS `motive_end_of_service`,`ocadmin_dbo`.`admin`.`startdate_inactivity` AS `startdate_inactivity`,`ocadmin_dbo`.`admin`.`enddate_inactivity` AS `enddate_inactivity`,`ocadmin_dbo`.`admin`.`code_inactivity` AS `code_inactivity`,`ocadmin_dbo`.`admin`.`update_status` AS `update_status`,`ocadmin_dbo`.`admin`.`person_type` AS `person_type`,`ocadmin_dbo`.`admin`.`situation_end_of_service` AS `situation_end_of_service`,`ocadmin_dbo`.`admin`.`updateuserid` AS `updateuserid`,`ocadmin_dbo`.`admin`.`comment1` AS `comment1`,`ocadmin_dbo`.`admin`.`comment2` AS `comment2`,`ocadmin_dbo`.`admin`.`comment3` AS `comment3`,`ocadmin_dbo`.`admin`.`comment4` AS `comment4`,`ocadmin_dbo`.`admin`.`comment5` AS `comment5`,`ocadmin_dbo`.`admin`.`natreg` AS `natreg`,`ocadmin_dbo`.`admin`.`middlename` AS `middlename`,`ocadmin_dbo`.`admin`.`begindate` AS `begindate`,`ocadmin_dbo`.`admin`.`enddate` AS `enddate`,`ocadmin_dbo`.`admin`.`updateserverid` AS `updateserverid`,`ocadmin_dbo`.`admin`.`archiveFileCode` AS `archiveFileCode` from `ocadmin_dbo`.`admin`;

-- ----------------------------
-- View structure for functionsview
-- ----------------------------
-- CREATE VIEW `functionsview` AS select `functionsview`.`workid` AS `workid`,`functionsview`.`functionid` AS `functionid`,`functionsview`.`functiontype` AS `functiontype`,`functionsview`.`labeltype` AS `labeltype`,`functionsview`.`labelid` AS `labelid`,`functionsview`.`labelnl` AS `labelnl`,`functionsview`.`labelfr` AS `labelfr`,`functionsview`.`labelen` AS `labelen` from `ocadmin_dbo`.`functionsview`;

-- ----------------------------
-- View structure for labelsview
-- ----------------------------
CREATE VIEW `labelsview` AS select `labels`.`labeltype` AS `labeltype`,`labels`.`labelid` AS `labelid`,`labels`.`labelnl` AS `labelnl`,`labels`.`labelfr` AS `labelfr`,`labels`.`labelen` AS `labelen` from `ocadmin_dbo`.`labels`;

-- ----------------------------
-- View structure for lastconvocation
-- ----------------------------
CREATE VIEW `lastconvocation` AS select `b`.`personId` AS `personid`,max(cast(concat(concat(concat(concat(substr(`c`.`value`,7,4),'/'),substr(`c`.`value`,4,2)),'/'),substr(`c`.`value`,1,2)) as datetime)) AS `lastconvocation` from ((`transactions` `a` join `healthrecord` `b`) join `items` `c`) where ((`a`.`healthRecordId` = `b`.`healthRecordId`) and (`a`.`transactionId` = `c`.`transactionId`) and (`a`.`serverid` = `c`.`serverid`) and (`a`.`transactionType` = 'be.mxs.common.model.vo.healthrecord.IConstants.TRANSACTION_TYPE_MER') and (`c`.`type` = 'be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_MER_EXAMINATION_DATE')) group by `b`.`personId`;

-- ----------------------------
-- View structure for lastdrivingcertificate
-- ----------------------------
CREATE VIEW `lastdrivingcertificate` AS select `b`.`personId` AS `personid`,max(`a`.`updateTime`) AS `lastconvocation` from (`transactions` `a` join `healthrecord` `b`) where ((`a`.`healthRecordId` = `b`.`healthRecordId`) and (`a`.`transactionType` = 'be.mxs.common.model.vo.healthrecord.IConstants.TRANSACTION_TYPE_DLC')) group by `b`.`personId`;

-- ----------------------------
-- View structure for mers
-- ----------------------------
CREATE VIEW `mers` AS select distinct `a`.`personId` AS `personId`,`c`.`value` AS `examinationDate`,`d`.`value` AS `convocationDate` from (((`healthrecord` `a` join `transactions` `b`) join `items` `c`) join `items` `d`) where ((`a`.`healthRecordId` = `b`.`healthRecordId`) and (`b`.`transactionType` = 'be.mxs.common.model.vo.healthrecord.IConstants.TRANSACTION_TYPE_MER') and (`b`.`transactionId` = `c`.`transactionId`) and (`b`.`serverid` = `c`.`serverid`) and (`b`.`transactionId` = `d`.`transactionId`) and (`b`.`serverid` = `d`.`serverid`) and (`c`.`type` = 'be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_MER_EXAMINATION_DATE') and (`d`.`type` = 'be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_MER_NEW_CONVOCATION_DATE'));

-- ----------------------------
-- View structure for oc_diagnoses_view
-- ----------------------------
CREATE VIEW `oc_diagnoses_view` AS select `a`.`OC_DIAGNOSIS_DATE` AS `OC_DIAGNOSIS_DATE`,`a`.`OC_DIAGNOSIS_ENCOUNTERUID` AS `OC_DIAGNOSIS_ENCOUNTERUID`,`a`.`OC_DIAGNOSIS_AUTHORUID` AS `OC_DIAGNOSIS_AUTHORUID`,`b`.`OC_DIAGNOSIS_GROUPCODE` AS `OC_DIAGNOSIS_CODE`,`a`.`OC_DIAGNOSIS_CODETYPE` AS `OC_DIAGNOSIS_CODETYPE`,`a`.`OC_DIAGNOSIS_CERTAINTY` AS `OC_DIAGNOSIS_CERTAINTY`,`a`.`OC_DIAGNOSIS_GRAVITY` AS `OC_DIAGNOSIS_GRAVITY`,`a`.`OC_DIAGNOSIS_ENDDATE` AS `OC_DIAGNOSIS_ENDDATE`,`a`.`OC_DIAGNOSIS_POA` AS `OC_DIAGNOSIS_POA`,`a`.`OC_DIAGNOSIS_NC` AS `OC_DIAGNOSIS_NC`,`a`.`OC_DIAGNOSIS_SERVICEUID` AS `OC_DIAGNOSIS_SERVICEUID`,`a`.`OC_DIAGNOSIS_ENCOUNTEROBJECTID` AS `OC_DIAGNOSIS_ENCOUNTEROBJECTID`,`a`.`OC_DIAGNOSIS_SERVERID` AS `OC_DIAGNOSIS_SERVERID`,`a`.`OC_DIAGNOSIS_OBJECTID` AS `OC_DIAGNOSIS_OBJECTID` from (`oc_diagnoses` `a` join `oc_diagnosis_groups` `b`) where ((`a`.`OC_DIAGNOSIS_CODE` >= `b`.`OC_DIAGNOSIS_CODESTART`) and (`a`.`OC_DIAGNOSIS_CODE` <= `b`.`OC_DIAGNOSIS_CODEEND`) and (`a`.`OC_DIAGNOSIS_CODETYPE` = `b`.`OC_DIAGNOSIS_CODETYPE`));

-- ----------------------------
-- View structure for oc_encounter_servicesview
-- ----------------------------
CREATE VIEW `oc_encounter_servicesview` AS select `oc_encounter_services`.`OC_ENCOUNTER_SERVERID` AS `OC_ENCOUNTER_SERVERID`,`oc_encounter_services`.`OC_ENCOUNTER_OBJECTID` AS `OC_ENCOUNTER_OBJECTID`,`oc_encounter_services`.`OC_ENCOUNTER_SERVICEUID` AS `OC_ENCOUNTER_SERVICEUID`,`oc_encounter_services`.`OC_ENCOUNTER_BEDUID` AS `OC_ENCOUNTER_BEDUID`,`oc_encounter_services`.`OC_ENCOUNTER_SERVICEENDDATE` AS `OC_ENCOUNTER_SERVICEENDDATE`,`oc_encounter_services`.`OC_ENCOUNTER_MANAGERUID` AS `OC_ENCOUNTER_MANAGERUID`,`oc_encounter_services`.`OC_ENCOUNTER_SERVICEBEGINDATE` AS `OC_ENCOUNTER_SERVICEBEGINDATE` from `oc_encounter_services`;

-- ----------------------------
-- View structure for oc_encounters_view
-- ----------------------------
CREATE VIEW `oc_encounters_view` AS select `a`.`OC_ENCOUNTER_SERVERID` AS `oc_encounter_serverid`,`a`.`OC_ENCOUNTER_OBJECTID` AS `oc_encounter_objectid`,`a`.`OC_ENCOUNTER_TYPE` AS `oc_encounter_type`,`b`.`OC_ENCOUNTER_SERVICEBEGINDATE` AS `OC_ENCOUNTER_BEGINDATE`,ifnull(`b`.`OC_ENCOUNTER_SERVICEENDDATE`,now()) AS `OC_ENCOUNTER_ENDDATE`,`a`.`OC_ENCOUNTER_PATIENTUID` AS `oc_encounter_patientuid`,`a`.`OC_ENCOUNTER_CREATETIME` AS `oc_encounter_createtime`,`a`.`OC_ENCOUNTER_UPDATETIME` AS `oc_encounter_updatetime`,`a`.`OC_ENCOUNTER_UPDATEUID` AS `oc_encounter_updateuid`,`a`.`OC_ENCOUNTER_VERSION` AS `oc_encounter_version`,`a`.`oc_encounter_outcome` AS `oc_encounter_outcome`,`a`.`OC_ENCOUNTER_DESTINATIONUID` AS `oc_encounter_destinationuid`,`a`.`OC_ENCOUNTER_ORIGIN` AS `oc_encounter_origin`,`a`.`OC_ENCOUNTER_SITUATION` AS `oc_encounter_situation`,`b`.`OC_ENCOUNTER_SERVICEUID` AS `oc_encounter_serviceuid`,`b`.`OC_ENCOUNTER_BEDUID` AS `oc_encounter_beduid`,`b`.`OC_ENCOUNTER_MANAGERUID` AS `oc_encounter_manageruid`,`a`.`OC_ENCOUNTER_CATEGORIES` AS `oc_encounter_categories` from (`oc_encounters` `a` join `oc_encounter_services` `b`) where ((`a`.`OC_ENCOUNTER_SERVERID` = `b`.`OC_ENCOUNTER_SERVERID`) and (`a`.`OC_ENCOUNTER_OBJECTID` = `b`.`OC_ENCOUNTER_OBJECTID`));

-- ----------------------------
-- View structure for oc_invoices_counterview
-- ----------------------------
CREATE VIEW `oc_invoices_counterview` AS select `oc_patientinvoices`.`OC_PATIENTINVOICE_OBJECTID` AS `OC_INVOICE_OBJECTID` from `oc_patientinvoices` union select `oc_insurarinvoices`.`OC_INSURARINVOICE_OBJECTID` AS `OC_INVOICE_OBJECTID` from `oc_insurarinvoices` union select `oc_extrainsurarinvoices`.`OC_INSURARINVOICE_OBJECTID` AS `OC_INVOICE_OBJECTID` from `oc_extrainsurarinvoices`;

-- ----------------------------
-- View structure for privateview
-- ----------------------------
CREATE VIEW `privateview` AS select `ocadmin_dbo`.`adminprivate`.`privateid` AS `privateid`,`ocadmin_dbo`.`adminprivate`.`personid` AS `personid`,`ocadmin_dbo`.`adminprivate`.`start` AS `start`,`ocadmin_dbo`.`adminprivate`.`stop` AS `stop`,`ocadmin_dbo`.`adminprivate`.`address` AS `address`,`ocadmin_dbo`.`adminprivate`.`city` AS `city`,`ocadmin_dbo`.`adminprivate`.`zipcode` AS `zipcode`,`ocadmin_dbo`.`adminprivate`.`country` AS `country`,`ocadmin_dbo`.`adminprivate`.`telephone` AS `telephone`,`ocadmin_dbo`.`adminprivate`.`fax` AS `fax`,`ocadmin_dbo`.`adminprivate`.`mobile` AS `mobile`,`ocadmin_dbo`.`adminprivate`.`email` AS `email`,`ocadmin_dbo`.`adminprivate`.`comment` AS `comment`,`ocadmin_dbo`.`adminprivate`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`adminprivate`.`type` AS `type`,`ocadmin_dbo`.`adminprivate`.`updateserverid` AS `updateserverid`,`ocadmin_dbo`.`adminprivate`.`district` AS `district`,`ocadmin_dbo`.`adminprivate`.`sanitarydistrict` AS `sanitarydistrict`,`ocadmin_dbo`.`adminprivate`.`province` AS `province`,`ocadmin_dbo`.`adminprivate`.`sector` AS `sector`,`ocadmin_dbo`.`adminprivate`.`cell` AS `cell`,`ocadmin_dbo`.`adminprivate`.`quarter` AS `quarter`,`ocadmin_dbo`.`adminprivate`.`business` AS `business`,`ocadmin_dbo`.`adminprivate`.`businessfunction` AS `businessfunction` from `ocadmin_dbo`.`adminprivate`;

-- ----------------------------
-- View structure for servicesaddressview
-- ----------------------------
CREATE VIEW `servicesaddressview` AS select cast(concat('0',`ocadmin_dbo`.`services`.`zipcode`) as signed) AS `zip`,`ocadmin_dbo`.`services`.`serviceid` AS `serviceid`,`ocadmin_dbo`.`services`.`address` AS `address`,`ocadmin_dbo`.`services`.`city` AS `city`,`ocadmin_dbo`.`services`.`zipcode` AS `zipcode`,`ocadmin_dbo`.`services`.`country` AS `country`,`ocadmin_dbo`.`services`.`telephone` AS `telephone`,`ocadmin_dbo`.`services`.`fax` AS `fax`,`ocadmin_dbo`.`services`.`comment` AS `comment`,`ocadmin_dbo`.`services`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`services`.`email` AS `email`,`ocadmin_dbo`.`services`.`parentid` AS `parentid`,`ocadmin_dbo`.`services`.`serviceparentid` AS `serviceparentid`,`ocadmin_dbo`.`services`.`inscode` AS `inscode`,`ocadmin_dbo`.`services`.`serviceorder` AS `serviceorder`,`ocadmin_dbo`.`services`.`servicelanguage` AS `servicelanguage`,`ocadmin_dbo`.`services`.`updateuserid` AS `updateuserid`,`ocadmin_dbo`.`services`.`parentserviceid` AS `parentserviceid`,`ocadmin_dbo`.`services`.`code1` AS `code1`,`ocadmin_dbo`.`services`.`code2` AS `code2`,`ocadmin_dbo`.`services`.`code3` AS `code3`,`ocadmin_dbo`.`services`.`code4` AS `code4`,`ocadmin_dbo`.`services`.`code5` AS `code5`,`ocadmin_dbo`.`services`.`contract` AS `contract`,`ocadmin_dbo`.`services`.`contracttype` AS `contracttype`,`ocadmin_dbo`.`services`.`contactperson` AS `contactperson`,`ocadmin_dbo`.`services`.`contractdate` AS `contractdate`,`ocadmin_dbo`.`services`.`portal_email` AS `portal_email`,`ocadmin_dbo`.`services`.`contactaddress` AS `contactaddress`,`ocadmin_dbo`.`services`.`contactzipcode` AS `contactzipcode`,`ocadmin_dbo`.`services`.`contactcity` AS `contactcity`,`ocadmin_dbo`.`services`.`contactcountry` AS `contactcountry`,`ocadmin_dbo`.`services`.`contacttelephone` AS `contacttelephone`,`ocadmin_dbo`.`services`.`contactfax` AS `contactfax`,`ocadmin_dbo`.`services`.`contactemail` AS `contactemail`,`ocadmin_dbo`.`services`.`ssn` AS `ssn`,`ocadmin_dbo`.`services`.`code6` AS `code6`,`ocadmin_dbo`.`services`.`defaultcontext` AS `defaultcontext`,`ocadmin_dbo`.`services`.`defaultservicestockuid` AS `defaultservicestockuid`,`ocadmin_dbo`.`services`.`wicket` AS `wicket`,`ocadmin_dbo`.`services`.`totalbeds` AS `totalbeds`,`ocadmin_dbo`.`services`.`inactive` AS `inactive` from `ocadmin_dbo`.`services`;

-- ----------------------------
-- View structure for servicesview
-- ----------------------------
CREATE VIEW `servicesview` AS select `ocadmin_dbo`.`services`.`serviceid` AS `serviceid`,`ocadmin_dbo`.`services`.`address` AS `address`,`ocadmin_dbo`.`services`.`city` AS `city`,`ocadmin_dbo`.`services`.`zipcode` AS `zipcode`,`ocadmin_dbo`.`services`.`country` AS `country`,`ocadmin_dbo`.`services`.`telephone` AS `telephone`,`ocadmin_dbo`.`services`.`fax` AS `fax`,`ocadmin_dbo`.`services`.`comment` AS `comment`,`ocadmin_dbo`.`services`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`services`.`email` AS `email`,`ocadmin_dbo`.`services`.`parentid` AS `parentid`,`ocadmin_dbo`.`services`.`serviceparentid` AS `serviceparentid`,`ocadmin_dbo`.`services`.`inscode` AS `inscode`,`ocadmin_dbo`.`services`.`serviceorder` AS `serviceorder`,`ocadmin_dbo`.`services`.`servicelanguage` AS `servicelanguage`,`ocadmin_dbo`.`services`.`updateuserid` AS `updateuserid`,`ocadmin_dbo`.`services`.`parentserviceid` AS `parentserviceid`,`ocadmin_dbo`.`services`.`code1` AS `code1`,`ocadmin_dbo`.`services`.`code2` AS `code2`,`ocadmin_dbo`.`services`.`code3` AS `code3`,`ocadmin_dbo`.`services`.`code4` AS `code4`,`ocadmin_dbo`.`services`.`code5` AS `code5`,`ocadmin_dbo`.`services`.`contract` AS `contract`,`ocadmin_dbo`.`services`.`contracttype` AS `contracttype`,`ocadmin_dbo`.`services`.`contactperson` AS `contactperson`,`ocadmin_dbo`.`services`.`contractdate` AS `contractdate`,`ocadmin_dbo`.`services`.`portal_email` AS `portal_email`,`ocadmin_dbo`.`services`.`contactaddress` AS `contactaddress`,`ocadmin_dbo`.`services`.`contactzipcode` AS `contactzipcode`,`ocadmin_dbo`.`services`.`contactcity` AS `contactcity`,`ocadmin_dbo`.`services`.`contactcountry` AS `contactcountry`,`ocadmin_dbo`.`services`.`contacttelephone` AS `contacttelephone`,`ocadmin_dbo`.`services`.`contactfax` AS `contactfax`,`ocadmin_dbo`.`services`.`contactemail` AS `contactemail`,`ocadmin_dbo`.`services`.`ssn` AS `ssn`,`ocadmin_dbo`.`services`.`code6` AS `code6`,`ocadmin_dbo`.`services`.`defaultcontext` AS `defaultcontext`,`ocadmin_dbo`.`services`.`defaultservicestockuid` AS `defaultservicestockuid`,`ocadmin_dbo`.`services`.`wicket` AS `wicket`,`ocadmin_dbo`.`services`.`totalbeds` AS `totalbeds`,`ocadmin_dbo`.`services`.`inactive` AS `inactive`,`ocadmin_dbo`.`services`.`costcenter` AS `costcenter`,`ocadmin_dbo`.`services`.`acceptsVisits` AS `acceptsVisits`,`ocadmin_dbo`.`services`.`performeruid` AS `performeruid`,`ocadmin_dbo`.`services`.`stayprestationuid` AS `stayprestationuid` from `ocadmin_dbo`.`services`;

-- ----------------------------
-- View structure for servicesviewyearreport
-- ----------------------------
CREATE VIEW `servicesviewyearreport` AS select `servicesview`.`workid` AS `workid`,`servicesview`.`serviceid` AS `serviceid`,`servicesview`.`servicetype` AS `servicetype`,`servicesview`.`OC_LABEL_TYPE` AS `OC_LABEL_TYPE`,`servicesview`.`OC_LABEL_ID` AS `OC_LABEL_ID`,`servicesview`.`OC_LABEL_LANGUAGE` AS `OC_LABEL_LANGUAGE`,`servicesview`.`OC_LABEL_VALUE` AS `OC_LABEL_VALUE` from `ocadmin_dbo`.`servicesview`;

-- ----------------------------
-- View structure for transactionview
-- ----------------------------
CREATE VIEW `transactionview` AS select `b`.`value` AS `value`,`a`.`userId` AS `userId`,`a`.`healthRecordId` AS `healthRecordId`,`a`.`transactionId` AS `transactionId`,`a`.`serverid` AS `serverid`,`a`.`transactionType` AS `transactionType`,`a`.`updateTime` AS `updateTime`,`a`.`ts` AS `ts` from (`transactions` `a` join `items` `b`) where ((`a`.`transactionId` = `b`.`transactionId`) and (`a`.`serverid` = `b`.`serverid`) and (`b`.`type` = 'be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT'));

-- ----------------------------
-- View structure for unitgroupsview
-- ----------------------------
CREATE VIEW `unitgroupsview` AS select cast(`groups`.`linkId` as signed) AS `intLinkId`,`groups`.`id` AS `id`,`groups`.`groupType` AS `groupType`,`groups`.`groupName` AS `groupName`,`groups`.`linkId` AS `linkId`,`groups`.`active` AS `active`,`groups`.`updatetime` AS `updatetime` from `groups` where (`groups`.`active` = 1);

-- ----------------------------
-- View structure for usersview
-- ----------------------------
CREATE VIEW `usersview` AS select `ocadmin_dbo`.`users`.`userid` AS `userid`,`ocadmin_dbo`.`users`.`personid` AS `personid`,`ocadmin_dbo`.`users`.`start` AS `start`,`ocadmin_dbo`.`users`.`stop` AS `stop`,`ocadmin_dbo`.`users`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`users`.`project` AS `project`,`ocadmin_dbo`.`users`.`encryptedpassword` AS `encryptedpassword`,`ocadmin_dbo`.`users`.`password` AS `password` from `ocadmin_dbo`.`users`;

-- ----------------------------
-- View structure for workview
-- ----------------------------
CREATE VIEW `workview` AS select `a`.`workid` AS `workid`,`a`.`personid` AS `personid`,`a`.`start` AS `start`,`a`.`stop` AS `stop`,`a`.`rankid` AS `rankid`,`a`.`telephone` AS `telephone`,`a`.`fax` AS `fax`,`a`.`email` AS `email`,`a`.`comment` AS `comment`,`a`.`updatetime` AS `updatetime`,`a`.`status` AS `status`,`a`.`statussituation` AS `statussituation`,`a`.`category` AS `category`,`a`.`companyBegin` AS `companyBegin`,`a`.`companyEnd` AS `companyEnd`,`a`.`companyEndReason` AS `companyEndReason`,`a`.`passive` AS `passive`,`a`.`functionBegin` AS `functionBegin`,`a`.`functionEnd` AS `functionEnd`,`a`.`updateserverid` AS `updateserverid`,(select `openclinic_dbo`.`oc_labels`.`OC_LABEL_VALUE` AS `OC_LABEL_VALUE` from `openclinic_dbo`.`oc_labels` where ((`openclinic_dbo`.`oc_labels`.`OC_LABEL_TYPE` = _latin1'service') and (`openclinic_dbo`.`oc_labels`.`OC_LABEL_ID` = `b`.`serviceid`) and (`openclinic_dbo`.`oc_labels`.`OC_LABEL_LANGUAGE` = _latin1'nl')) limit 1) AS `labelnl`,(select `openclinic_dbo`.`oc_labels`.`OC_LABEL_VALUE` AS `OC_LABEL_VALUE` from `openclinic_dbo`.`oc_labels` where ((`openclinic_dbo`.`oc_labels`.`OC_LABEL_TYPE` = _latin1'service') and (`openclinic_dbo`.`oc_labels`.`OC_LABEL_ID` = `b`.`serviceid`) and (`openclinic_dbo`.`oc_labels`.`OC_LABEL_LANGUAGE` = _latin1'fr')) limit 1) AS `labelfr`,`b`.`servicetype` AS `servicetype`,`b`.`serviceid` AS `serviceid` from (`ocadmin_dbo`.`adminwork` `a` join `ocadmin_dbo`.`adminservices` `b`) where (`a`.`workid` = `b`.`workid`);

-- ----------------------------
-- View structure for workview2
-- ----------------------------
CREATE VIEW `workview2` AS select `ocadmin_dbo`.`adminwork`.`workid` AS `workid`,`ocadmin_dbo`.`adminwork`.`personid` AS `personid`,`ocadmin_dbo`.`adminwork`.`start` AS `start`,`ocadmin_dbo`.`adminwork`.`stop` AS `stop`,`ocadmin_dbo`.`adminwork`.`rankid` AS `rankid`,`ocadmin_dbo`.`adminwork`.`telephone` AS `telephone`,`ocadmin_dbo`.`adminwork`.`fax` AS `fax`,`ocadmin_dbo`.`adminwork`.`email` AS `email`,`ocadmin_dbo`.`adminwork`.`comment` AS `comment`,`ocadmin_dbo`.`adminwork`.`updatetime` AS `updatetime`,`ocadmin_dbo`.`adminwork`.`status` AS `status`,`ocadmin_dbo`.`adminwork`.`statussituation` AS `statussituation`,`ocadmin_dbo`.`adminwork`.`category` AS `category`,`ocadmin_dbo`.`adminwork`.`companyBegin` AS `companyBegin`,`ocadmin_dbo`.`adminwork`.`companyEnd` AS `companyEnd`,`ocadmin_dbo`.`adminwork`.`companyEndReason` AS `companyEndReason`,`ocadmin_dbo`.`adminwork`.`passive` AS `passive`,`ocadmin_dbo`.`adminwork`.`functionBegin` AS `functionBegin`,`ocadmin_dbo`.`adminwork`.`functionEnd` AS `functionEnd`,`ocadmin_dbo`.`adminwork`.`updateserverid` AS `updateserverid` from `ocadmin_dbo`.`adminwork`;
